version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: home-db
    environment:
      - POSTGRES_DB=home-db-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisisnotactualpasswordlol
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data
volumes:
  db:
    driver: local
      

